steps:
  # Download credential files from Cloud Storage
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'gs://barkit-credential/firebaseAccountKey2.json', 'config/firebaseAccountKey2.json']
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'gs://barkit-credential/firebaseClientConfig2.json', 'config/firebaseClientConfig2.json']
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'gs://barkit-credential/cloudStorageKey2.json', 'config/cloudStorageKey2.json']

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/${_SERVICE_NAME}/${_IMAGE_NAME}:${SHORT_SHA}', '.']
    id: 'Building the container image'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/${_SERVICE_NAME}/${_IMAGE_NAME}:${SHORT_SHA}']
    id: 'Pushing the image to registry'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud' 
    args: ['run', 'deploy', '${_IMAGE_NAME}', '--image', 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/${_SERVICE_NAME}/${_IMAGE_NAME}:${SHORT_SHA}', '--region', 'asia-southeast2', '--platform', 'managed', "--allow-unauthenticated"]